### ISSUE TITLE
Installation fails on Raw Edition 2.1.0p15

### ISSUE THREAD

**Issue by FingerlessGlov3s** [inettgmbh/checkmk-proxmox_backup_server#3]
Just went to install this on my Checkmk Raw Edition 2.1.0p15 but it fails to load the plugin unfortunately.

Steps taken to install
```
cd tmp
wget https://github.com/inettgmbh/checkmk-proxmox_backup_server/releases/download/0.3.8/proxmox_bs-0.3.8.mkp
mkp install proxmox_bs-0.3.8.mkp
rm proxmox_bs-0.3.8.mkp
```

Analyze configuration output
```
CRIT: Loading "/omd/sites/icy/local/share/check_mk/web/plugins/wato/proxmox_bs.py" failed: No module named 'cmk.gui.cee' (!!)
```

Anyone know a fix or workaround?

EDIT: I think it maybe because I don't have the enterprise version, but I can't test this theory.

**Comment by Jay2k1** [comment]
Hi,

I just installed the lastest (pre-)release 0.3.9-rc1 and it works fine. I am on the raw edition too (albeit 2.1.0p23). 

When I analyze the configuration, it too complains in `Broken GUI extensions` about this missing module, amongst a few other things from other plugins, but it works nonetheless. Seeing it has `cee` in its name, which stands for checkmk enterprise edition, I too suspect that it's something specific to that edition.

Since it works well regardless, I wouldn't consider this an installation failure but rather a minor annoyance (this error will pop up whenever you update your instance).

![image](https://user-images.githubusercontent.com/2070503/224329231-69ed6b50-eaab-4cba-ab76-89b2c2994e1b.png)
<sub>do we know each other from thelounge?</sub>
